name: Compile and publish résumé PDF

on:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/**"
            - "static/**"
            - CNAME
            - "index.html"
            - "resume.tex"
    pull_request:
        branches:
            - main
        paths:
            - ".github/workflows/**"
            - "static/**"
            - CNAME
            - "index.html"
            - "resume.tex"
    workflow_dispatch: # Allows manual execution of workflow

jobs:
    build-latex:
        runs-on: ubuntu-latest
        container:
            image: danteev/texlive:latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@v2
              with:
                  root_file: resume.tex

            - name: Post Processing
              run: |
                  mkdir build 
                  cp -r static/ build/
                  cp CNAME build/
                  cp favicon.ico build/
                  cp index.html build/
                  cp resume.pdf build/
                  mv "build/resume.pdf" "build/Résumé for Harsh Kapadia.pdf"

            - name: Git add
              run: git add "build/Résumé for Harsh Kapadia.pdf"

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  BRANCH: gh-pages
                  FOLDER: build
                  CLEAN: true
